/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.guilford.outfitpickerproject;

import java.util.ArrayList;

/**
 *
 * @author cshad
 */
public class FitcheckPanel extends javax.swing.JPanel {

    // Attributes
    private ArrayList<Fitcheck> outfits;
    private int outfitIndex;

    // Constructors
    public FitcheckPanel() {
        initComponents();
    }

    public FitcheckPanel(ArrayList<Fitcheck> outfits) {
        initComponents();
        this.outfits = outfits;
        System.out.println(outfits.get(0).getShirt());
        shirtOTD.setText(outfits.get(0).getShirt());
        bottomOTD.setText(outfits.get(0).getBottom());
        shoesOTD.setText(outfits.get(0).getShoes());
        jacketOTD.setText(outfits.get(0).getJacket());
        glassesOTD.setText(outfits.get(0).getGlasses());
        bagOTD.setText(outfits.get(0).getBag());
        jewelryOTD.setText(outfits.get(0).getSilverJewelry());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        climateButtonGroup = new javax.swing.ButtonGroup();
        occasionButtonGroup = new javax.swing.ButtonGroup();
        coldButton = new javax.swing.JRadioButton();
        warmButton = new javax.swing.JRadioButton();
        hotButton = new javax.swing.JRadioButton();
        chillButton = new javax.swing.JRadioButton();
        casualButton = new javax.swing.JRadioButton();
        formalButton = new javax.swing.JRadioButton();
        generateButton = new javax.swing.JButton();
        wearButton = new javax.swing.JButton();
        likeButton = new javax.swing.JButton();
        shirtOTD = new javax.swing.JTextField();
        bottomOTD = new javax.swing.JTextField();
        shoesOTD = new javax.swing.JTextField();
        jacketOTD = new javax.swing.JTextField();
        glassesOTD = new javax.swing.JTextField();
        bagOTD = new javax.swing.JTextField();
        jewelryOTD = new javax.swing.JTextField();
        climateLabel = new javax.swing.JLabel();
        occasionLabel = new javax.swing.JLabel();
        shirtLabel = new javax.swing.JLabel();
        bottomLabel = new javax.swing.JLabel();
        shoesLabel = new javax.swing.JLabel();
        jacketLabel = new javax.swing.JLabel();
        glassesLabel = new javax.swing.JLabel();
        bagLabel = new javax.swing.JLabel();
        jewelryLabel = new javax.swing.JLabel();
        wornShirt = new javax.swing.JTextField();
        wornBottom = new javax.swing.JTextField();
        wornShoes = new javax.swing.JTextField();
        wornJacket = new javax.swing.JTextField();
        wornGlasses = new javax.swing.JTextField();
        wornBag = new javax.swing.JTextField();
        wornJewelry = new javax.swing.JTextField();
        shirtLabel1 = new javax.swing.JLabel();
        bottomLabel1 = new javax.swing.JLabel();
        shoesLabel1 = new javax.swing.JLabel();
        jacketLabel1 = new javax.swing.JLabel();
        glassesLabel1 = new javax.swing.JLabel();
        bagLabel1 = new javax.swing.JLabel();
        jewelryLabel1 = new javax.swing.JLabel();
        likedShirt = new javax.swing.JTextField();
        likedBottom = new javax.swing.JTextField();
        likedShoes = new javax.swing.JTextField();
        likedJacket = new javax.swing.JTextField();
        likedGlasses = new javax.swing.JTextField();
        likedBag = new javax.swing.JTextField();
        likedJewelry = new javax.swing.JTextField();
        shirtLabel2 = new javax.swing.JLabel();
        bottomLabel2 = new javax.swing.JLabel();
        shoesLabel2 = new javax.swing.JLabel();
        jacketLabel2 = new javax.swing.JLabel();
        glassesLabel2 = new javax.swing.JLabel();
        bagLabel2 = new javax.swing.JLabel();
        jewelryLabel2 = new javax.swing.JLabel();

        climateButtonGroup.add(coldButton);
        coldButton.setText("Cold");
        coldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coldButtonActionPerformed(evt);
            }
        });

        climateButtonGroup.add(warmButton);
        warmButton.setSelected(true);
        warmButton.setText("Warm");
        warmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warmButtonActionPerformed(evt);
            }
        });

        climateButtonGroup.add(hotButton);
        hotButton.setText("Hot");
        hotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotButtonActionPerformed(evt);
            }
        });

        occasionButtonGroup.add(chillButton);
        chillButton.setText("Chill");
        chillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chillButtonActionPerformed(evt);
            }
        });

        occasionButtonGroup.add(casualButton);
        casualButton.setSelected(true);
        casualButton.setText("Casual");
        casualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casualButtonActionPerformed(evt);
            }
        });

        occasionButtonGroup.add(formalButton);
        formalButton.setText("Formal");
        formalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formalButtonActionPerformed(evt);
            }
        });

        generateButton.setText("Generate!");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        wearButton.setText("Wear");
        wearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wearButtonActionPerformed(evt);
            }
        });

        likeButton.setText("Like <3");
        likeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likeButtonActionPerformed(evt);
            }
        });

        shirtOTD.setText("\"\"");
        shirtOTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shirtOTDActionPerformed(evt);
            }
        });

        bottomOTD.setText("\"\"");
        bottomOTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottomOTDActionPerformed(evt);
            }
        });

        shoesOTD.setText("\"\"");
        shoesOTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoesOTDActionPerformed(evt);
            }
        });

        jacketOTD.setText("\"\"");
        jacketOTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jacketOTDActionPerformed(evt);
            }
        });

        glassesOTD.setText("\"\"");
        glassesOTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                glassesOTDActionPerformed(evt);
            }
        });

        bagOTD.setText("\"\"");
        bagOTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagOTDActionPerformed(evt);
            }
        });

        jewelryOTD.setText("\"\"");
        jewelryOTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jewelryOTDActionPerformed(evt);
            }
        });

        climateLabel.setText("Please select the climate of the day:");

        occasionLabel.setText("Please select the occasion of the day:");

        shirtLabel.setText("Shirt:");

        bottomLabel.setText("Bottoms:");

        shoesLabel.setText("Shoes:");

        jacketLabel.setText("Jacket:");

        glassesLabel.setText("Glasses:");

        bagLabel.setText("Bag:");

        jewelryLabel.setText("Jewelry:");

        wornShirt.setText("\"\"");
        wornShirt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wornShirtActionPerformed(evt);
            }
        });

        wornBottom.setText("\"\"");
        wornBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wornBottomActionPerformed(evt);
            }
        });

        wornShoes.setText("\"\"");
        wornShoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wornShoesActionPerformed(evt);
            }
        });

        wornJacket.setText("\"\"");
        wornJacket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wornJacketActionPerformed(evt);
            }
        });

        wornGlasses.setText("\"\"");
        wornGlasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wornGlassesActionPerformed(evt);
            }
        });

        wornBag.setText("\"\"");
        wornBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wornBagActionPerformed(evt);
            }
        });

        wornJewelry.setText("\"\"");
        wornJewelry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wornJewelryActionPerformed(evt);
            }
        });

        shirtLabel1.setText("Shirt:");

        bottomLabel1.setText("Bottoms:");

        shoesLabel1.setText("Shoes:");

        jacketLabel1.setText("Jacket:");

        glassesLabel1.setText("Glasses:");

        bagLabel1.setText("Bag:");

        jewelryLabel1.setText("Jewelry:");

        likedShirt.setText("\"\"");
        likedShirt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likedShirtActionPerformed(evt);
            }
        });

        likedBottom.setText("\"\"");
        likedBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likedBottomActionPerformed(evt);
            }
        });

        likedShoes.setText("\"\"");
        likedShoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likedShoesActionPerformed(evt);
            }
        });

        likedJacket.setText("\"\"");
        likedJacket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likedJacketActionPerformed(evt);
            }
        });

        likedGlasses.setText("\"\"");
        likedGlasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likedGlassesActionPerformed(evt);
            }
        });

        likedBag.setText("\"\"");
        likedBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likedBagActionPerformed(evt);
            }
        });

        likedJewelry.setText("\"\"");
        likedJewelry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likedJewelryActionPerformed(evt);
            }
        });

        shirtLabel2.setText("Shirt:");

        bottomLabel2.setText("Bottoms:");

        shoesLabel2.setText("Shoes:");

        jacketLabel2.setText("Jacket:");

        glassesLabel2.setText("Glasses:");

        bagLabel2.setText("Bag:");

        jewelryLabel2.setText("Jewelry:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(climateLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(warmButton)
                    .addComponent(coldButton)
                    .addComponent(hotButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(occasionLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casualButton)
                            .addComponent(chillButton)
                            .addComponent(formalButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(wearButton)))
                .addGap(159, 159, 159)
                .addComponent(generateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 286, Short.MAX_VALUE)
                .addComponent(likeButton)
                .addGap(117, 117, 117))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(shirtLabel1)
                                .addComponent(bottomLabel1)
                                .addComponent(shoesLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jacketLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(glassesLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bagLabel1)
                            .addGap(61, 61, 61)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jewelryLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(wornBag, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(wornGlasses, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wornJacket, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wornShoes, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wornShirt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wornBottom, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wornJewelry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(shirtLabel)
                                .addComponent(bottomLabel)
                                .addComponent(shoesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jacketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(glassesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bagLabel)
                            .addGap(61, 61, 61)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jewelryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bagOTD, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(glassesOTD, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shoesOTD, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bottomOTD, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shirtOTD, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jacketOTD)
                    .addComponent(jewelryOTD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(shirtLabel2)
                                .addComponent(bottomLabel2)
                                .addComponent(shoesLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jacketLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(glassesLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bagLabel2)
                            .addGap(61, 61, 61)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jewelryLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(likedGlasses, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(likedJacket, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(likedShoes, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(likedBottom, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(likedShirt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(likedBag)
                    .addComponent(likedJewelry))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(coldButton)
                    .addComponent(climateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warmButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hotButton)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chillButton)
                    .addComponent(occasionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(casualButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formalButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(shirtLabel)
                                    .addComponent(shirtOTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bottomLabel)
                                    .addComponent(bottomOTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(shoesLabel)
                                    .addComponent(shoesOTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jacketLabel)
                                    .addComponent(jacketOTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(glassesLabel)
                                    .addComponent(glassesOTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bagLabel)
                                    .addComponent(bagOTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jewelryLabel)
                                    .addComponent(jewelryOTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(shirtLabel1)
                                    .addComponent(wornShirt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bottomLabel1)
                                    .addComponent(wornBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(shoesLabel1)
                                    .addComponent(wornShoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jacketLabel1)
                                    .addComponent(wornJacket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(glassesLabel1)
                                    .addComponent(wornGlasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bagLabel1)
                                    .addComponent(wornBag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jewelryLabel1)
                                    .addComponent(wornJewelry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wearButton)
                            .addComponent(likeButton)
                            .addComponent(generateButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shirtLabel2)
                            .addComponent(likedShirt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bottomLabel2)
                            .addComponent(likedBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shoesLabel2)
                            .addComponent(likedShoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jacketLabel2)
                            .addComponent(likedJacket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(glassesLabel2)
                            .addComponent(likedGlasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bagLabel2)
                            .addComponent(likedBag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jewelryLabel2)
                            .addComponent(likedJewelry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void warmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warmButtonActionPerformed
        // TODO add your handling code here:
        outfits.get(outfitIndex).setWeather("Warml");
    }//GEN-LAST:event_warmButtonActionPerformed

    private void hotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotButtonActionPerformed
        // TODO add your handling code here:
        outfits.get(outfitIndex).setWeather("Hot");
    }//GEN-LAST:event_hotButtonActionPerformed

    private void chillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chillButtonActionPerformed
        // TODO add your handling code here:
        outfits.get(outfitIndex).setOccasion("Chill");
    }//GEN-LAST:event_chillButtonActionPerformed

    private void formalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formalButtonActionPerformed
        // TODO add your handling code here:
        outfits.get(outfitIndex).setOccasion("Formal");
    }//GEN-LAST:event_formalButtonActionPerformed

    private void coldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coldButtonActionPerformed
        // TODO add your handling code here:
        outfits.get(outfitIndex).setWeather("Cold");
    }//GEN-LAST:event_coldButtonActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        // TODO add your handling code here:
        outfits.clear();
        //Fitcheck OOTD = new Fitcheck();
        for (var a = 0; a < 5; a++) {
        outfits.add(new Fitcheck());
        }
        updateInfo();
    }//GEN-LAST:event_generateButtonActionPerformed

    private void glassesOTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_glassesOTDActionPerformed
        // TODO add your handling code here:
        String glassesString = glassesOTD.getText();
        glassesOTD.setText(glassesString);
        outfits.get(0).setGlasses(glassesString);
    }//GEN-LAST:event_glassesOTDActionPerformed

    private void casualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casualButtonActionPerformed
        // TODO add your handling code here:
        outfits.get(outfitIndex).setOccasion("Casual");
    }//GEN-LAST:event_casualButtonActionPerformed

    private void wearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wearButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<Fitcheck> wornOutfits = new ArrayList<Fitcheck>();
        wornOutfits.add(outfits.get(0));
        updateWorn();
    }//GEN-LAST:event_wearButtonActionPerformed

    private void likeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likeButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<Fitcheck> likedOutfits = new ArrayList<Fitcheck>();
        likedOutfits.add(outfits.get(0));
        updateLiked();
    }//GEN-LAST:event_likeButtonActionPerformed

    private void shirtOTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shirtOTDActionPerformed
        // TODO add your handling code here:
        String shirtString = shirtOTD.getText();
        shirtOTD.setText(shirtString);
        outfits.get(0).setShirt(shirtString);
    }//GEN-LAST:event_shirtOTDActionPerformed

    private void jewelryOTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jewelryOTDActionPerformed
        // TODO add your handling code here:
        String jewelryString = jewelryOTD.getText();
        jewelryOTD.setText(jewelryString);
        outfits.get(0).setSilverJewelry(jewelryString);      
    }//GEN-LAST:event_jewelryOTDActionPerformed

    private void bottomOTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottomOTDActionPerformed
        // TODO add your handling code here:
        String bottomString = bottomOTD.getText();
        bottomOTD.setText(bottomString);
        outfits.get(0).setBottom(bottomString);
    }//GEN-LAST:event_bottomOTDActionPerformed

    private void shoesOTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoesOTDActionPerformed
        // TODO add your handling code here:
        String shoesString = shoesOTD.getText();
        shoesOTD.setText(shoesString);
        outfits.get(0).setShoes(shoesString);
    }//GEN-LAST:event_shoesOTDActionPerformed

    private void jacketOTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jacketOTDActionPerformed
        // TODO add your handling code here:
        String jacketString = jacketOTD.getText();
        jacketOTD.setText(jacketString);
        outfits.get(0).setJacket(jacketString);
    }//GEN-LAST:event_jacketOTDActionPerformed

    private void bagOTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagOTDActionPerformed
        // TODO add your handling code here:
        String bagString = bagOTD.getText();
        bagOTD.setText(bagString);
        outfits.get(0).setBag(bagString);
    }//GEN-LAST:event_bagOTDActionPerformed

    private void wornShirtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wornShirtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wornShirtActionPerformed

    private void wornBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wornBottomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wornBottomActionPerformed

    private void wornShoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wornShoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wornShoesActionPerformed

    private void wornJacketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wornJacketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wornJacketActionPerformed

    private void wornGlassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wornGlassesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wornGlassesActionPerformed

    private void wornBagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wornBagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wornBagActionPerformed

    private void wornJewelryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wornJewelryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wornJewelryActionPerformed

    private void likedShirtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likedShirtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_likedShirtActionPerformed

    private void likedBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likedBottomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_likedBottomActionPerformed

    private void likedShoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likedShoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_likedShoesActionPerformed

    private void likedJacketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likedJacketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_likedJacketActionPerformed

    private void likedGlassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likedGlassesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_likedGlassesActionPerformed

    private void likedBagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likedBagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_likedBagActionPerformed

    private void likedJewelryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likedJewelryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_likedJewelryActionPerformed

    
    private void updateInfo() {
        shirtOTD.setText(outfits.get(outfitIndex).getShirt());
        bottomOTD.setText(outfits.get(outfitIndex).getBottom());
        shoesOTD.setText(outfits.get(outfitIndex).getShoes());
        jacketOTD.setText(outfits.get(outfitIndex).getJacket());
        glassesOTD.setText(outfits.get(outfitIndex).getGlasses());
        bagOTD.setText(outfits.get(outfitIndex).getBag());
        jewelryOTD.setText(outfits.get(outfitIndex).getSilverJewelry());        
    }
    
    private void updateLiked() {
        likedShirt.setText(outfits.get(outfitIndex).getShirt());
        likedBottom.setText(outfits.get(outfitIndex).getBottom());
        likedShoes.setText(outfits.get(outfitIndex).getShoes());
        likedJacket.setText(outfits.get(outfitIndex).getJacket());
        likedGlasses.setText(outfits.get(outfitIndex).getGlasses());
        likedBag.setText(outfits.get(outfitIndex).getBag());
        likedJewelry.setText(outfits.get(outfitIndex).getSilverJewelry());        
    }
    
    private void updateWorn() {
        wornShirt.setText(outfits.get(outfitIndex).getShirt());
        wornBottom.setText(outfits.get(outfitIndex).getBottom());
        wornShoes.setText(outfits.get(outfitIndex).getShoes());
        wornJacket.setText(outfits.get(outfitIndex).getJacket());
        wornGlasses.setText(outfits.get(outfitIndex).getGlasses());
        wornBag.setText(outfits.get(outfitIndex).getBag());
        wornJewelry.setText(outfits.get(outfitIndex).getSilverJewelry());        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bagLabel;
    private javax.swing.JLabel bagLabel1;
    private javax.swing.JLabel bagLabel2;
    private javax.swing.JTextField bagOTD;
    private javax.swing.JLabel bottomLabel;
    private javax.swing.JLabel bottomLabel1;
    private javax.swing.JLabel bottomLabel2;
    private javax.swing.JTextField bottomOTD;
    private javax.swing.JRadioButton casualButton;
    private javax.swing.JRadioButton chillButton;
    private javax.swing.ButtonGroup climateButtonGroup;
    private javax.swing.JLabel climateLabel;
    private javax.swing.JRadioButton coldButton;
    private javax.swing.JRadioButton formalButton;
    private javax.swing.JButton generateButton;
    private javax.swing.JLabel glassesLabel;
    private javax.swing.JLabel glassesLabel1;
    private javax.swing.JLabel glassesLabel2;
    private javax.swing.JTextField glassesOTD;
    private javax.swing.JRadioButton hotButton;
    private javax.swing.JLabel jacketLabel;
    private javax.swing.JLabel jacketLabel1;
    private javax.swing.JLabel jacketLabel2;
    private javax.swing.JTextField jacketOTD;
    private javax.swing.JLabel jewelryLabel;
    private javax.swing.JLabel jewelryLabel1;
    private javax.swing.JLabel jewelryLabel2;
    private javax.swing.JTextField jewelryOTD;
    private javax.swing.JButton likeButton;
    private javax.swing.JTextField likedBag;
    private javax.swing.JTextField likedBottom;
    private javax.swing.JTextField likedGlasses;
    private javax.swing.JTextField likedJacket;
    private javax.swing.JTextField likedJewelry;
    private javax.swing.JTextField likedShirt;
    private javax.swing.JTextField likedShoes;
    private javax.swing.ButtonGroup occasionButtonGroup;
    private javax.swing.JLabel occasionLabel;
    private javax.swing.JLabel shirtLabel;
    private javax.swing.JLabel shirtLabel1;
    private javax.swing.JLabel shirtLabel2;
    private javax.swing.JTextField shirtOTD;
    private javax.swing.JLabel shoesLabel;
    private javax.swing.JLabel shoesLabel1;
    private javax.swing.JLabel shoesLabel2;
    private javax.swing.JTextField shoesOTD;
    private javax.swing.JRadioButton warmButton;
    private javax.swing.JButton wearButton;
    private javax.swing.JTextField wornBag;
    private javax.swing.JTextField wornBottom;
    private javax.swing.JTextField wornGlasses;
    private javax.swing.JTextField wornJacket;
    private javax.swing.JTextField wornJewelry;
    private javax.swing.JTextField wornShirt;
    private javax.swing.JTextField wornShoes;
    // End of variables declaration//GEN-END:variables
}
